### ISSUE TITLE
Module FBAudienceNetwork not found

### ISSUE THREAD

**Issue by ronak301** [7kfpun/AudienceNetworkReactNative#1]

**Comment by 7kfpun** [comment]
Update packages https://github.com/7kfpun/FinanceReactNative/commit/a46560910dfb79e9cf73552a0d202537e09538f0

**Comment by 7kfpun** [comment]
Download the SDK and unzip the archive to ~/Documents/FacebookSDK would fix.
https://developers.facebook.com/docs/ios/getting-started#download

**Comment by apersaud** [comment]
I wanted to continue using cocoapods for dependency management, so I replaced all `@import FBAudienceNetwork` with `#import <FBAudienceNetwork/FBAudienceNetwork.h>` and that fixed it. If you are a Swift only app, you may need ot create a bridging header.
